export const ROUTE = {
  HOME: "/",
  CONTEST_SUBMISSION: "/tong-hop-bai-du-thi",
  LOGIN: "/dang-nhap",
  ADMIN: "/quan-ly",
  NEWS_FEED: "/bang-tin",
  NEWS: "/tin-tuc",
  EVENTS: "/su-kien",
  HIRING: "/tuyen-dung",
  MODERATOR: "/phe-duyet",
  SHOP: "/cua-hang",
  MISSION: "/nhiem-vu",
  ACHIEVEMENT: "/thanh-tuu",
  PROFILE: "/ho-so",
  //Sub Route admin
  MY_CLASS: "/lop-hoc-cua-toi",
  ACCOUNT: "/quan-ly-tai-khoan",
  COURSES: "/khoa-hoc",
  AVATAR_SHOP: "/anh-dai-dien",
  BACKGROUND_SHOP: "/hinh-nen",
};
